name: Validate

on:
  push:
    branches: [ data ]
  pull_request:
    branches: [ data ]

jobs:
  check-schema:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get check/jsonschema
      run: pip install check-jsonschema
    - name: Check JSON schema
      run: check-jsonschema --schemafile schema.json */curves.json
  check-ecgen:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get ecgen
      run: |
        wget "https://github.com/J08nY/ecgen/releases/latest/download/ecgen-static"
        chmod +x ./ecgen-static
    - name: Check the curves
      run: ./.github/workflows/validate.sh
  check-sagemath:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get SageMath
      run: |
        conda config --add channels conda-forge
        conda create -n sage sage python=3.11
    - name: Check the curves
      run: |
        conda activate sage
        sage ./.github/workflows/validate.sage
