name: Order check

on:
  push:
    branches: [ data ]
  pull_request:
    branches: [ data ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - name: Get ecgen
      run: |
        wget "https://github.com/J08nY/ecgen/releases/latest/download/ecgen-static"
        chmod +x ./ecgen-static
    - name: Check the curves
      run: ./.github/workflows/validate.sh
        
